
from fpdf import FPDF

class PDF(FPDF):
    l_margin: float = 10
    r_margin: float = 10

    def header(self):
        self.set_y(3)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(100, 100, 100)
        header_right_text = f"TAX YEAR 2022-23"
        self.set_x(-(self.get_string_width(header_right_text) + 8))
        self.cell(self.get_string_width(header_right_text), 10,
                  header_right_text, align="L", border=0, new_x="LMARGIN", new_y="NEXT")

    def footer(self):
        # Position cursor at 1.5 cm from bottom:
        self.set_y(-12)
        # Setting font: helvetica italic 8
        self.set_font("helvetica", "I", 8)
        # get page width using predefined method
        page_w = self.w

        # footer text
        footer_text = "generated by revbook "
        self.set_text_color(140, 140, 140)
        self.cell(self.get_string_width(footer_text), 10,
                  footer_text, align="L", border=False, new_x="RIGHT")

        # Printing page number:
        # page_number_string = f"Page {self.page_no()}/{{nb}}"
        # self.set_x(-(self.get_string_width(page_number_string) + 10))
        # self.cell(self.get_string_width(page_number_string), 10,
        #           page_number_string, align="L", border=False, new_x="RIGHT")

        # self.cell(self)
    def left_para(self, heading_name=None, description=None, value=None, heading_font_size=18, desc_font_size=9, border_value=0, head_style="", desc_style='', head_cell_height=5, desc_cell_height=5):
        # pdf.set_text_color(100,100,100)
        header_left_text = heading_name
        if value:
            self.set_font("helvetica", head_style, heading_font_size)
            self.set_x(self.l_margin)
            self.cell(self.w//2 - 30, head_cell_height, str(value),
                      align="R", border=border_value, new_x="LMARGIN")

        if header_left_text:
            self.set_font("helvetica", head_style, heading_font_size)
            self.set_x(self.l_margin)
            self.cell(self.get_string_width(header_left_text), head_cell_height, header_left_text,
                      align="L", border=border_value, new_x="LMARGIN", new_y="NEXT")

        if description:
            self.set_font("helvetica", desc_style, desc_font_size)
            description_text = description
            # self.set_x(pdf.l_margin)
            self.cell((self.w//2) - ((self.l_margin*2) + self.r_margin), desc_cell_height, description_text,
                      align="L", border=border_value, new_x="LMARGIN", new_y="NEXT")

    def right_para(self, heading_name=None, description=None, value=None, heading_font_size=18, desc_font_size=9, border_value=0, head_style="", desc_style='', head_cell_height=5, desc_cell_height=5):

        # pdf.set_text_color(100,100,100)
        self.set_x((self.w//2) + (self.l_margin//2))
        if value:
            self.set_font("helvetica", head_style, heading_font_size)
            # self.set_x(self.l_margin)
            self.cell(self.w//2 - 30, head_cell_height, str(value),
                      align="R", border=border_value, new_x="LEFT")
        header_right_text = heading_name
        if header_right_text:
            self.set_font("helvetica", head_style, heading_font_size)
            rr = (self.w//2) + (self.l_margin//2)
            self.cell(self.get_string_width(header_right_text), head_cell_height, header_right_text,
                      align="L", border=border_value, new_x="LEFT", new_y="NEXT")

        if description:
            self.set_font("helvetica", desc_style, desc_font_size)
            description_text = description
            # self.set_x(pdf.l_margin)
            self.cell((self.w//2) - ((self.l_margin*2) + self.r_margin), desc_cell_height, description_text,
                      align="L", border=border_value, new_x="LMARGIN", new_y="NEXT")
            


# COPY FROM HERE !!!!!!!!!!!
pdf = PDF("P",'mm','Letter')

pdf.add_page()
# Tile
pdf.set_font("helvetica", "", 21)
pdf.cell(0, 10, "Tax Report 2022 - 23",align="C",new_x="LMARGIN",new_y="NEXT")
# pdf.left_para(heading_name="Tax Report 2022 - 23", )
#-------------------- title done------------

# for gap/spacing
pdf.left_para(description=" ")
pdf.left_para(description=" ")
pdf.left_para(description=" ")

# Date: 01/10/2022 17:33 (dynamic)
date_val = "01/10/2022 17:33"
pdf.left_para(heading_name=f"Date: {date_val}", heading_font_size=12)
# pdf.cell(0, 10, "Tax Report 2022 - 23",align="C",new_x="LMARGIN",new_y="NEXT")

# Period: 1 Apr 2022 to 31 Mar 2023
period_val = "1 Apr 2022 to 31 Mar 2023"
pdf.left_para(heading_name=f"Period: {period_val}", heading_font_size=12, head_cell_height=9)

pdf.left_para(description=" ")
pdf.left_para(description=" ")

# Content
pdf.left_para(heading_name="Content", heading_font_size=14, head_cell_height=9)

content_list = ["Capital gains summary","Income summary","Asset Summary","End of Year Balances","Capital Gains Transactions","Income Transactions","Gifts, Donations & lost assets","Data sources","Expenses"]

count = 1
for content in content_list:
    pdf.left_para(heading_name=f"{count}. {content}", heading_font_size=12, head_cell_height=6)
    count+=1
#-----------------content end -------------------
pdf.left_para(description=" ")
pdf.left_para(description=" ")
pdf.left_para(description=" ")



pdf.set_x(pdf.l_margin-3)
pdf.cell(pdf.w - (pdf.l_margin*2) + 6, 50, " ", border=1, new_x="LMARGIN")




###############################
pdf.left_para(description=" ")
pdf.set_font_size(10.1)
pdf.multi_cell(pdf.w - (pdf.l_margin*2) , 5, "All fiat values and prices are in INR unless stated otherwise. Capital gains have been calculated using the FIFO accounting method (universal tax lot for each currency). Trading between cryptocurrencies is treated as a taxable event. Market prices are determined using the average market value at the time of the disposal - unless the price is provided by the trading platform or manually overridden. All dates and times are in the Asia/Kolkata timezone. \n\nThis report may be used for tax purposes after it has been checked for accuracy and completeness by yourself or your tax advisor.", border=0)
###############################

###############################
# pdf.left_para(description=" ")
# pdf.left_para(heading_name="All fiat values and prices are in INR unless stated otherwise. Capital gains have been calculated using the FIFO accounting", heading_font_size=10)
# pdf.left_para(heading_name="method (universal tax lot for each currency). Trading between cryptocurrencies is treated as a taxable event. Market prices", heading_font_size=10)
# pdf.left_para(heading_name="are determined using the average market value at the time of the disposal - unless the price is provided by the trading ", heading_font_size=10)
# pdf.left_para(heading_name="platform or manually overridden. All dates and times are in the Asia/Kolkata timezone.", heading_font_size=10)
# pdf.left_para(description=" ")


# pdf.left_para(heading_name="This report may be used for tax purposes after it has been checked for accuracy and completeness by yourself or your", heading_font_size=10)
# pdf.left_para(heading_name="tax advisor.", heading_font_size=10)
################################### 

pdf.output("first.pdf")
print("File saved")
    
    
    
    
# "All fiat values and prices are in INR unless stated otherwise. Capital gains have been calculated using the FIFO accounting method (universal tax lot for each currency). Trading between cryptocurrencies is treated as a taxable event. Market prices are determined using the average market value at the time of the disposal - unless the price is provided by the trading platform or manually overridden. All dates and times are in the Asia/Kolkata timezone. 

# This report may be used for tax purposes after it has been checked for accuracy and completeness by yourself or your tax advisor."
